package term

import (
	"github.com/RyanTKing/reddix/pkg/event"
	termbox "github.com/nsf/termbox-go"
)

var termboxKeys = map[termbox.Key]string{
	termbox.KeySpace:      event.KeySpace,
	termbox.KeyTab:        event.KeyTab,
	termbox.KeyBackspace2: event.KeyBackspace,
	termbox.KeyEnter:      event.KeyEnter,
	termbox.KeyArrowUp:    event.KeyArrowUp,
	termbox.KeyArrowDown:  event.KeyArrowDown,
	termbox.KeyArrowLeft:  event.KeyArrowLeft,
	termbox.KeyArrowRight: event.KeyArrowRight,
	termbox.KeyEsc:        event.KeyEsc,
	termbox.KeyF1:         event.KeyF1,
	termbox.KeyF2:         event.KeyF2,
	termbox.KeyF3:         event.KeyF3,
	termbox.KeyF4:         event.KeyF4,
	termbox.KeyF5:         event.KeyF5,
	termbox.KeyF6:         event.KeyF6,
	termbox.KeyF7:         event.KeyF7,
	termbox.KeyF8:         event.KeyF8,
	termbox.KeyF9:         event.KeyF9,
	termbox.KeyF10:        event.KeyF10,
	termbox.KeyF11:        event.KeyF11,
	termbox.KeyF12:        event.KeyF12,
	termbox.KeyInsert:     event.KeyInsert,
	termbox.KeyDelete:     event.KeyDelete,
	termbox.KeyHome:       event.KeyHome,
	termbox.KeyEnd:        event.KeyEnd,
	termbox.KeyPgup:       event.KeyPageUp,
	termbox.KeyPgdn:       event.KeyPageDown,
	termbox.KeyCtrlA:      event.KeyCtrlA,
	termbox.KeyCtrlB:      event.KeyCtrlB,
	termbox.KeyCtrlC:      event.KeyCtrlC,
	termbox.KeyCtrlD:      event.KeyCtrlD,
	termbox.KeyCtrlE:      event.KeyCtrlE,
	termbox.KeyCtrlF:      event.KeyCtrlF,
	termbox.KeyCtrlG:      event.KeyCtrlG,
	termbox.KeyCtrlJ:      event.KeyCtrlJ,
	termbox.KeyCtrlK:      event.KeyCtrlK,
	termbox.KeyCtrlL:      event.KeyCtrlL,
	termbox.KeyCtrlN:      event.KeyCtrlN,
	termbox.KeyCtrlO:      event.KeyCtrlO,
	termbox.KeyCtrlP:      event.KeyCtrlP,
	termbox.KeyCtrlQ:      event.KeyCtrlQ,
	termbox.KeyCtrlR:      event.KeyCtrlR,
	termbox.KeyCtrlS:      event.KeyCtrlS,
	termbox.KeyCtrlT:      event.KeyCtrlT,
	termbox.KeyCtrlU:      event.KeyCtrlU,
	termbox.KeyCtrlV:      event.KeyCtrlV,
	termbox.KeyCtrlW:      event.KeyCtrlW,
	termbox.KeyCtrlX:      event.KeyCtrlX,
	termbox.KeyCtrlY:      event.KeyCtrlY,
	termbox.KeyCtrlZ:      event.KeyCtrlZ,
	termbox.KeyCtrl4:      event.KeyCtrl4,
	termbox.KeyCtrl5:      event.KeyCtrl5,
	termbox.KeyCtrl6:      event.KeyCtrl6,
	termbox.KeyCtrl7:      event.KeyCtrl7,
	termbox.KeyCtrlSpace:  event.KeyCtrlSpace,
	termbox.KeyBackspace:  event.KeyCtrlBackspace,
}
